/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.java.desktop_java;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.event.*;
/**
 *
 * @author Achraf
 */
public class demandeNonTraite extends javax.swing.JFrame {
    String CNE = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    int tabSel =0;
    DefaultTableModel model;
    /**
     * Creates new form demandeNonTraite
     */
    public demandeNonTraite() {
        initComponents();
      TableConventionStage();
      TableReleveNote();
      TableAttestationScolarite();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        deconnecter1 = new javax.swing.JButton();
        menu1 = new javax.swing.JButton();
        retour1 = new javax.swing.JButton();
        kGradientPanel8 = new keeptoo.KGradientPanel();
        menu2 = new javax.swing.JButton();
        retour2 = new javax.swing.JButton();
        deconnecter2 = new javax.swing.JButton();
        kGradientPanel9 = new keeptoo.KGradientPanel();
        menu3 = new javax.swing.JButton();
        retour3 = new javax.swing.JButton();
        deconnecter3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel7 = new keeptoo.KGradientPanel();
        menu = new javax.swing.JButton();
        retour = new javax.swing.JButton();
        deconnecter = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ConvensionTable = new javax.swing.JTable();
        search_conv = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        saved = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        AttestationTable = new javax.swing.JTable();
        search_attest = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ReleveTable = new javax.swing.JTable();
        search_releve = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        X = new java.awt.Button();

        jMenuItem1.setText("jMenuItem1");

        kGradientPanel6.setEndColor(new java.awt.Color(0, 51, 51));
        kGradientPanel6.setStartColor(new java.awt.Color(0, 102, 102));

        deconnecter1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deconnecter1.setForeground(new java.awt.Color(0, 102, 102));
        deconnecter1.setText("Déconnecter");
        deconnecter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnecter1ActionPerformed(evt);
            }
        });

        menu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu1.setForeground(new java.awt.Color(0, 102, 102));
        menu1.setText("Menu");
        menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu1ActionPerformed(evt);
            }
        });

        retour1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        retour1.setForeground(new java.awt.Color(0, 102, 102));
        retour1.setText("retour");
        retour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retour1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel6Layout = new javax.swing.GroupLayout(kGradientPanel6);
        kGradientPanel6.setLayout(kGradientPanel6Layout);
        kGradientPanel6Layout.setHorizontalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel6Layout.createSequentialGroup()
                        .addComponent(deconnecter1)
                        .addGap(2, 2, 2))
                    .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retour1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        kGradientPanel6Layout.setVerticalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retour1)
                .addGap(173, 173, 173)
                .addComponent(menu1)
                .addGap(13, 13, 13)
                .addComponent(deconnecter1)
                .addGap(40, 40, 40))
        );

        kGradientPanel8.setEndColor(new java.awt.Color(0, 51, 51));
        kGradientPanel8.setStartColor(new java.awt.Color(0, 102, 102));

        menu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu2.setForeground(new java.awt.Color(0, 102, 102));
        menu2.setText("Menu");
        menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu2ActionPerformed(evt);
            }
        });

        retour2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        retour2.setForeground(new java.awt.Color(0, 102, 102));
        retour2.setText("Retour");
        retour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retour2ActionPerformed(evt);
            }
        });

        deconnecter2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deconnecter2.setForeground(new java.awt.Color(0, 102, 102));
        deconnecter2.setText("Se deconnecter");

        javax.swing.GroupLayout kGradientPanel8Layout = new javax.swing.GroupLayout(kGradientPanel8);
        kGradientPanel8.setLayout(kGradientPanel8Layout);
        kGradientPanel8Layout.setHorizontalGroup(
            kGradientPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel8Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(kGradientPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(retour2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deconnecter2))
                .addGap(41, 41, 41))
        );
        kGradientPanel8Layout.setVerticalGroup(
            kGradientPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel8Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(retour2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu2)
                .addGap(18, 18, 18)
                .addComponent(deconnecter2)
                .addGap(37, 37, 37))
        );

        kGradientPanel9.setEndColor(new java.awt.Color(0, 51, 51));
        kGradientPanel9.setStartColor(new java.awt.Color(0, 102, 102));

        menu3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu3.setForeground(new java.awt.Color(0, 102, 102));
        menu3.setText("Menu");
        menu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu3ActionPerformed(evt);
            }
        });

        retour3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        retour3.setForeground(new java.awt.Color(0, 102, 102));
        retour3.setText("Retour");
        retour3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retour3ActionPerformed(evt);
            }
        });

        deconnecter3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deconnecter3.setForeground(new java.awt.Color(0, 102, 102));
        deconnecter3.setText("Se deconnecter");

        javax.swing.GroupLayout kGradientPanel9Layout = new javax.swing.GroupLayout(kGradientPanel9);
        kGradientPanel9.setLayout(kGradientPanel9Layout);
        kGradientPanel9Layout.setHorizontalGroup(
            kGradientPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel9Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(kGradientPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(retour3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deconnecter3))
                .addGap(41, 41, 41))
        );
        kGradientPanel9Layout.setVerticalGroup(
            kGradientPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel9Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(retour3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu3)
                .addGap(18, 18, 18)
                .addComponent(deconnecter3)
                .addGap(37, 37, 37))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        kGradientPanel7.setEndColor(new java.awt.Color(0, 51, 51));
        kGradientPanel7.setStartColor(new java.awt.Color(0, 102, 102));

        menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu.setForeground(new java.awt.Color(0, 102, 102));
        menu.setText("Menu");
        menu.setBorderPainted(false);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        retour.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        retour.setForeground(new java.awt.Color(0, 102, 102));
        retour.setText("Retour");
        retour.setBorderPainted(false);
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });

        deconnecter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deconnecter.setForeground(new java.awt.Color(0, 102, 102));
        deconnecter.setText("Se déconnecter");
        deconnecter.setBorderPainted(false);
        deconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnecterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel7Layout = new javax.swing.GroupLayout(kGradientPanel7);
        kGradientPanel7.setLayout(kGradientPanel7Layout);
        kGradientPanel7Layout.setHorizontalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel7Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(retour, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deconnecter))
                .addGap(41, 41, 41))
        );
        kGradientPanel7Layout.setVerticalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel7Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(retour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu)
                .addGap(18, 18, 18)
                .addComponent(deconnecter)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        ConvensionTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ConvensionTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ConvensionTable.setForeground(new java.awt.Color(0, 102, 102));
        ConvensionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNE", "Nom", "Prenom", "Email", "date demande"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ConvensionTable.setGridColor(new java.awt.Color(0, 0, 0));
        ConvensionTable.setMinimumSize(new java.awt.Dimension(200, 40));
        ConvensionTable.setSelectionBackground(new java.awt.Color(0, 153, 153));
        ConvensionTable.getTableHeader().setResizingAllowed(false);
        ConvensionTable.getTableHeader().setReorderingAllowed(false);
        ConvensionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConvensionTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ConvensionTable);

        search_conv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_convActionPerformed(evt);
            }
        });
        search_conv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_convKeyReleased(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 51, 51));
        jLabel1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Rechercher :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(saved, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_conv, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 81, Short.MAX_VALUE)
                .addComponent(saved)
                .addGap(247, 247, 247))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(search_conv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Convention de stage", jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        AttestationTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AttestationTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AttestationTable.setForeground(new java.awt.Color(0, 102, 102));
        AttestationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNE", "Nom", "Prenom", "Email", "date demande"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        AttestationTable.setGridColor(new java.awt.Color(0, 0, 0));
        AttestationTable.setMinimumSize(new java.awt.Dimension(200, 20));
        AttestationTable.setSelectionBackground(new java.awt.Color(0, 153, 153));
        AttestationTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        AttestationTable.getTableHeader().setResizingAllowed(false);
        AttestationTable.getTableHeader().setReorderingAllowed(false);
        AttestationTable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AttestationTableMouseMoved(evt);
            }
        });
        AttestationTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AttestationTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(AttestationTable);

        search_attest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_attestKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Rechercher :");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search_attest, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_attest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Attestation de scolarité", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        ReleveTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ReleveTable.setForeground(new java.awt.Color(0, 102, 102));
        ReleveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNE", "Nom", "Prenom", "Email", "date demande"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ReleveTable.setGridColor(new java.awt.Color(0, 0, 0));
        ReleveTable.setIntercellSpacing(new java.awt.Dimension(5, 5));
        ReleveTable.setMinimumSize(new java.awt.Dimension(200, 20));
        ReleveTable.setSelectionBackground(new java.awt.Color(0, 153, 153));
        ReleveTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReleveTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(ReleveTable);
        if (ReleveTable.getColumnModel().getColumnCount() > 0) {
            ReleveTable.getColumnModel().getColumn(1).setPreferredWidth(10);
        }

        search_releve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_releveActionPerformed(evt);
            }
        });
        search_releve.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_releveKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Rechercher :");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search_releve, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_releve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Relevé de notes", jPanel7);

        X.setLabel("X");
        X.setName("X"); // NOI18N
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //ConvensionTable
    private void ConvensionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConvensionTableMouseClicked
                 // TODO add your handling code here:
         try {
             
            int i = ConvensionTable.getSelectedRow();
            
            TableModel tm =ConvensionTable.getModel();   
            
            CNE =tm.getValueAt(i, 0).toString();
            
            //************************************
            try {
            ps = (PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select id from gl_projet.etudiants where cne=?");
            ps.setString(1,CNE);
            rs = ps.executeQuery();
            int id=0;           
            if(rs.next()){
              id = rs.getInt("id");
             
              ps = (PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select id_demande  from gl_projet.demande_docs where id_etudiant=?  and created_at=?");
              ps.setInt(1,id);   
              ps.setString(2,tm.getValueAt(i, 4).toString());
              rs = ps.executeQuery();
              int id_demande;
             
              if(rs.next()){   
                  id_demande=rs.getInt("id_demande");
                  ConventionStage a = new ConventionStage(id_demande,id);
                  a.setVisible(true);
                   this.dispose();
              } 
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection failed 1!!!");
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection failed 2");
        }
    }//GEN-LAST:event_ConvensionTableMouseClicked

    private void AttestationTableMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttestationTableMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_AttestationTableMouseMoved
/*
    private void AttestationTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AttestationTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AttestationTableMouseClicked

    private void ReleveTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReleveTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ReleveTableMouseClicked

    private void search_releveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_releveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_releveActionPerformed
*/
    private void search_releveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_releveKeyReleased
        // TODO add your handling code here:
        String SearchString = search_releve.getText();
        search3(SearchString);
    }//GEN-LAST:event_search_releveKeyReleased

    private void search_attestKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_attestKeyReleased
        // TODO add your handling code here:
        String SearchString = search_attest.getText();
        search2(SearchString);
    }//GEN-LAST:event_search_attestKeyReleased

    private void search_convKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_convKeyReleased
        // TODO add your handling code here:
        String SearchString = search_conv.getText();
        search(SearchString);
    }//GEN-LAST:event_search_convKeyReleased

    private void search_convActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_convActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_convActionPerformed

    private void deconnecter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnecter1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deconnecter1ActionPerformed

    private void menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu1ActionPerformed
        // TODO add your handling code here:
        Demande_archive ar = new Demande_archive();
        ar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu1ActionPerformed

    private void retour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retour1ActionPerformed
        // TODO add your handling code here:
        Archive ar = new Archive();
        ar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_retour1ActionPerformed

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
        
       Demande_archive ar = new Demande_archive();
       ar.setVisible(true);
       this.dispose();

    }//GEN-LAST:event_retourActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
         Demande_archive ar = new Demande_archive();
       ar.setVisible(true);
       this.dispose(); 
    }//GEN-LAST:event_menuActionPerformed

    private void menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu2ActionPerformed

    private void retour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retour2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retour2ActionPerformed

    private void menu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu3ActionPerformed

    private void retour3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retour3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retour3ActionPerformed

    private void deconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnecterActionPerformed
        // TODO add your handling code here:
        LogAdmin menu = new LogAdmin();
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_deconnecterActionPerformed

    private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_XActionPerformed

      
    //AttestationTable
    private void AttestationTableMouseClicked(java.awt.event.MouseEvent evt) {                                             
                 // TODO add your handling code here:
         try {
             
            int i = AttestationTable.getSelectedRow();
            //ok.setText( Integer.toString(i));
            TableModel tm =AttestationTable.getModel();   
            
            CNE =tm.getValueAt(i, 0).toString();
            //ok.setText( CNE);
            //************************************
            try {
            ps = (PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select id from gl_projet.etudiants where cne=?");
            ps.setString(1,CNE);
            rs = ps.executeQuery();
            int id=0;           
            if(rs.next()){
              id = rs.getInt("id");
              //JOptionPane.showMessageDialog(null, id);
             //ok.setText(Integer.toString(id));
             //ok.setText(tm.getValueAt(i, 4).toString());
              ps = (PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select * from gl_projet.demande_docs where type_demande='attestation scolarite' and id_etudiant=?  and created_at=?");
              ps.setInt(1,id);   
              ps.setString(2,tm.getValueAt(i, 4).toString()); 
              rs = ps.executeQuery();
               
              int id_demande;
              if(rs.next()){ 
                  //JOptionPane.showMessageDialog(null, "connection ");
                  id_demande=rs.getInt("id_demande");
                  //JOptionPane.showMessageDialog(null, id_demande);
                  AttestationScolarite a = new AttestationScolarite(id_demande,id);
                  a.setVisible(true);
                  this.dispose();
              } 
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection failed 1!!!");
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection failed 2");
        }
    }          
    //ReleverTable
        private void ReleveTableMouseClicked(java.awt.event.MouseEvent evt){                                             
                 // TODO add your handling code here:
         try {
             
            int i = ReleveTable.getSelectedRow();
            TableModel tm =ReleveTable.getModel();   
            
            CNE =tm.getValueAt(i, 0).toString();
            
            //************************************
            try {
            ps = (PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select id from gl_projet.etudiants where cne=?");
            ps.setString(1,CNE);
            rs = ps.executeQuery();
            int id=0;           
            if(rs.next()){
              id = rs.getInt("id");
             
              ps = (PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select id_demande  from gl_projet.demande_docs where id_etudiant=? and type_demande='releve de notes' and created_at=?");
              ps.setInt(1,id);   
              ps.setString(2,tm.getValueAt(i, 4).toString());
              rs = ps.executeQuery();
              int id_demande;
             
              if(rs.next()){   
                  id_demande=rs.getInt("id_demande");
                  ReleveNote a = new ReleveNote(id_demande,id);
                   a.setVisible(true);
                   this.dispose();
              } 
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection failed 1!!!");
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection failed 2");
        }
    }
        public void TableConventionStage(){
     String enregistrer [] = {"CNE","Prénom","Nom","Email","Date Demande"};
     String afficher[] = new String[5];
     DefaultTableModel model = new DefaultTableModel(null,enregistrer);
     try{
          PreparedStatement ps;
          ps = ConnectionDB.getConnexion().prepareStatement("select * from gl_projet.demande_docs where is_archive=? and type_demande=?");
          ps.setString(1,"0");
          ps.setString(2,"convention stage");
          ResultSet rs = ps.executeQuery();
        while(rs.next()){
             afficher[4]=rs.getString("created_at");
            int id_etud = rs.getInt("id_etudiant");
             PreparedStatement ps2 =  ConnectionDB.getConnexion().prepareStatement("select * from gl_projet.etudiants where id=?");
             ps2.setString(1, Integer.toString(id_etud));
             ResultSet rs2 = ps2.executeQuery();

             if(rs2.next()){
                afficher[0]=rs2.getString("cne");
                afficher[1]=rs2.getString("prenom");
                afficher[2]=rs2.getString("nom"); 
                afficher[3]=rs2.getString("email_etudiant");   
             }
             model.addRow(afficher);
        }
        ConvensionTable.setModel(model);
     }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection failed!!!");
        }
    }
       public void TableAttestationScolarite(){
     String enregistrer [] = {"CNE","Prénom","Nom","Email","Date Demande"};
     String afficher[] = new String[5];
     DefaultTableModel model = new DefaultTableModel(null,enregistrer);
     try{
          PreparedStatement ps;
          ps = ConnectionDB.getConnexion().prepareStatement("select * from gl_projet.demande_docs where is_archive=? and type_demande=? ");
          ps.setString(1,"0");
          ps.setString(2,"attestation scolarite");
          ResultSet rs = ps.executeQuery();
        while(rs.next()){
            afficher[4]=rs.getString("created_at");
            int id_etud = rs.getInt("id_etudiant");
             PreparedStatement ps2 =  ConnectionDB.getConnexion().prepareStatement("select * from gl_projet.etudiants where id=? ");
             ps2.setString(1, Integer.toString(id_etud));
             ResultSet rs2 = ps2.executeQuery();
             if(rs2.next()){
                afficher[0]=rs2.getString("cne");
                afficher[1]=rs2.getString("prenom");
                afficher[2]=rs2.getString("nom"); 
                afficher[3]=rs2.getString("email_etudiant");   
             }
             model.addRow(afficher);
        }
        AttestationTable.setModel(model);
     }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection failed!!!");
        }
    }
       public void TableReleveNote(){
     String enregistrer [] = {"CNE","Prénom","Nom","Email","Date Demande"};
     String afficher[] = new String[5];
     DefaultTableModel model = new DefaultTableModel(null,enregistrer);
     try{
          PreparedStatement ps;
          ps = ConnectionDB.getConnexion().prepareStatement("select * from gl_projet.demande_docs where is_archive=? and type_demande=?");
          ps.setString(1,"0");
          ps.setString(2,"releve de notes");
          ResultSet rs = ps.executeQuery();
        while(rs.next()){    
            afficher[4]=rs.getString("created_at");
            int id_etud = rs.getInt("id_etudiant");
            PreparedStatement ps2 =  ConnectionDB.getConnexion().prepareStatement("select * from gl_projet.etudiants where id=?");
            ps2.setString(1, Integer.toString(id_etud));
            ResultSet rs2 = ps2.executeQuery();

             if(rs2.next()){
                afficher[0]=rs2.getString("cne");
                afficher[1]=rs2.getString("prenom");
                afficher[2]=rs2.getString("nom"); 
                afficher[3]=rs2.getString("email_etudiant");   
             }
             model.addRow(afficher);
        }
        ReleveTable.setModel(model);
     }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "connection failed!!!");
        }
    }
       public void search(String str){
        model = (DefaultTableModel)ConvensionTable .getModel();
        TableRowSorter<DefaultTableModel>trs = new TableRowSorter<>(model);
        ConvensionTable.setRowSorter(trs);      
        trs.setRowFilter(RowFilter.regexFilter(str));
    }
       public void search2(String str){
        model = (DefaultTableModel)AttestationTable .getModel();
        TableRowSorter<DefaultTableModel>trs = new TableRowSorter<>(model);
        AttestationTable.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }
       public void search3(String str){
        model = (DefaultTableModel)ReleveTable.getModel();
        TableRowSorter<DefaultTableModel>trs = new TableRowSorter<>(model);
        ReleveTable.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(demandeNonTraite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(demandeNonTraite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(demandeNonTraite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(demandeNonTraite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new demandeNonTraite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AttestationTable;
    private javax.swing.JTable ConvensionTable;
    private javax.swing.JTable ReleveTable;
    private java.awt.Button X;
    private javax.swing.JButton deconnecter;
    private javax.swing.JButton deconnecter1;
    private javax.swing.JButton deconnecter2;
    private javax.swing.JButton deconnecter3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private keeptoo.KGradientPanel kGradientPanel6;
    private keeptoo.KGradientPanel kGradientPanel7;
    private keeptoo.KGradientPanel kGradientPanel8;
    private keeptoo.KGradientPanel kGradientPanel9;
    private javax.swing.JButton menu;
    private javax.swing.JButton menu1;
    private javax.swing.JButton menu2;
    private javax.swing.JButton menu3;
    private javax.swing.JButton retour;
    private javax.swing.JButton retour1;
    private javax.swing.JButton retour2;
    private javax.swing.JButton retour3;
    private javax.swing.JLabel saved;
    private javax.swing.JTextField search_attest;
    private javax.swing.JTextField search_conv;
    private javax.swing.JTextField search_releve;
    // End of variables declaration//GEN-END:variables
}
