/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.java.desktop_java;

import java.awt.Desktop;
import java.io.File;
import java.sql.*;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.Authenticator;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.*;


/**
 *
 * @author HP
 */
public class Releve extends javax.swing.JFrame {
Connection conn = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    String niveau_e="";
    int semestre;
    int id_etu,id_demande; 
    
    public Releve(int id,int id_etud) {
        initComponents();
        try {
                      id_etu=id_etud;
                      id_demande=id;
                      ps = (PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select niveau,semestre from gl_projet.releve_notes where id=?");
                      ps.setInt(1,id);
                      rs = ps.executeQuery();
                      
                      if(rs.next()){
                          niveau_e=rs.getString("niveau");
                          semestre=rs.getInt("semestre");
                          niveau.setText(rs.getString("niveau")); 
                         
                      if(rs.getInt("semestre")==1){
                             jRadioButton1.setSelected(true);
                             jRadioButton2.setEnabled(false);
                             jRadioButton3.setEnabled(false);
                             jRadioButton1.setEnabled(false);
                         }
                         else if(rs.getInt("semestre")==2){
                             jRadioButton2.setSelected(true);
                             jRadioButton2.setEnabled(false);
                             jRadioButton3.setEnabled(false);
                             jRadioButton1.setEnabled(false);
                         }
                         else{
                             jRadioButton3.setSelected(true);
                             jRadioButton2.setEnabled(false);
                             jRadioButton3.setEnabled(false);
                             jRadioButton1.setEnabled(false);
                             
                         }
        }                   
                       niveau.setEditable(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        semesterRadio = new javax.swing.JPanel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        envoyer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        niveau = new javax.swing.JTextField();
        download = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        X = new java.awt.Button();
        kGradientPanel6 = new keeptoo.KGradientPanel();
        deconnecter = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        retour = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 0, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Niveau");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Semestre");

        semesterRadio.setBackground(new java.awt.Color(0, 102, 102));

        jRadioButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("TOUT");

        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("SEMESTRE 1");

        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("SEMESTRE 2");

        javax.swing.GroupLayout semesterRadioLayout = new javax.swing.GroupLayout(semesterRadio);
        semesterRadio.setLayout(semesterRadioLayout);
        semesterRadioLayout.setHorizontalGroup(
            semesterRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semesterRadioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(semesterRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton1)
                    .addGroup(semesterRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jRadioButton3)
                        .addComponent(jRadioButton2)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        semesterRadioLayout.setVerticalGroup(
            semesterRadioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, semesterRadioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        envoyer.setBackground(new java.awt.Color(0, 102, 102));
        envoyer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        envoyer.setForeground(new java.awt.Color(255, 255, 255));
        envoyer.setText("Envoyer");
        envoyer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envoyerActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Visualisation des données");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        niveau.setBackground(new java.awt.Color(0, 102, 102));
        niveau.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        niveau.setForeground(new java.awt.Color(255, 255, 255));
        niveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niveauActionPerformed(evt);
            }
        });

        download.setBackground(new java.awt.Color(0, 102, 102));
        download.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        download.setForeground(new java.awt.Color(255, 255, 255));
        download.setText("Télécharger");
        download.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));

        X.setLabel("X");
        X.setName("X"); // NOI18N
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(niveau, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(download)
                                .addGap(18, 18, 18)
                                .addComponent(envoyer))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(semesterRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel2))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {download, envoyer});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(niveau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(semesterRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(envoyer)
                    .addComponent(download))
                .addGap(24, 24, 24))
        );

        kGradientPanel6.setEndColor(new java.awt.Color(0, 51, 51));
        kGradientPanel6.setStartColor(new java.awt.Color(0, 102, 102));

        deconnecter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deconnecter.setForeground(new java.awt.Color(0, 102, 102));
        deconnecter.setText("Se déconnecter");
        deconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnecterActionPerformed(evt);
            }
        });

        menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menu.setForeground(new java.awt.Color(0, 102, 102));
        menu.setText("Menu");
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        retour.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        retour.setForeground(new java.awt.Color(0, 102, 102));
        retour.setText("Retour");
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel6Layout = new javax.swing.GroupLayout(kGradientPanel6);
        kGradientPanel6.setLayout(kGradientPanel6Layout);
        kGradientPanel6Layout.setHorizontalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel6Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(deconnecter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(retour, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        kGradientPanel6Layout.setVerticalGroup(
            kGradientPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel6Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(retour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deconnecter)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kGradientPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
        // TODO add your handling code here:
         Archive ar = new Archive();
         ar.setVisible(true);
         this.dispose();
          
    }//GEN-LAST:event_retourActionPerformed

    private void deconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnecterActionPerformed
        // TODO add your handling code here:
        LogAdmin menu = new LogAdmin();
        menu.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_deconnecterActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        // TODO add your handling code here:
        Demande_archive ar = new Demande_archive();
       ar.setVisible(true);
       this.dispose();   
    }//GEN-LAST:event_menuActionPerformed

    private void niveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niveauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_niveauActionPerformed

    private void downloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadActionPerformed
        // TODO add your handling code here:
        try {
            if(rs.getInt("semestre")==1){
                PreparedStatement pst1 =((PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select * from modules,etudiants,modules_etudiants,demande_docs,releve_notes where modules_etudiants.id_module = modules.id and modules_etudiants.id_etudiant=etudiants.id and demande_docs.id_etudiant = etudiants.id and releve_notes.id=demande_docs.id_demande and modules.niveau=? and etudiants.id=? and demande_docs.id_demande=?;"));
String conca = niveau_e+Integer.toString(semestre);
pst1.setString(1,conca);

pst1.setString(2,Integer.toString(id_etu));

pst1.setString(3,Integer.toString(id_demande));

ResultSet rs1 = pst1.executeQuery();

rs1.next();

String path ="D:\\javadirectories\\repos\\relever_note_"+rs1.getString("code_apogee")+"_"+id_demande+".pdf";
//open pdf fine	
File myFile = new File(path);
Desktop.getDesktop().open(myFile);
            }else if(rs.getInt("semestre")==2){
            PreparedStatement pst1 =((PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select * from modules,etudiants,modules_etudiants,demande_docs,releve_notes where modules_etudiants.id_module = modules.id and modules_etudiants.id_etudiant=etudiants.id and demande_docs.id_etudiant = etudiants.id and releve_notes.id=demande_docs.id_demande and modules.niveau=? and etudiants.id=? and demande_docs.id_demande=?;"));
            String conca = niveau_e+Integer.toString(semestre);
pst1.setString(1,conca);

pst1.setString(2,Integer.toString(id_etu));

pst1.setString(3,Integer.toString(id_demande));

ResultSet rs1 = pst1.executeQuery();

rs1.next();

String path ="D:\\javadirectories\\repos\\relever_note_2_"+rs1.getString("code_apogee")+"_"+id_demande+".pdf";
//open pdf fine	
File myFile = new File(path);
Desktop.getDesktop().open(myFile);
                
            }else{
                PreparedStatement pst1 =((PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select * from modules,etudiants,modules_etudiants,demande_docs,releve_notes where modules_etudiants.id_module = modules.id and modules_etudiants.id_etudiant=etudiants.id and demande_docs.id_etudiant = etudiants.id and releve_notes.id=demande_docs.id_demande and (modules.niveau=? or modules.niveau=?) and etudiants.id=? and demande_docs.id_demande=?;"));
                             
                             String conca = niveau_e+"1";
                             String conca2 = niveau_e+"2";
                             pst1.setString(1,conca);
                             
                             pst1.setString(2,conca2);
                             
                             pst1.setString(3,Integer.toString(id_etu));
                             
                             pst1.setString(4,Integer.toString(id_demande));
                             
                             ResultSet rs1 = pst1.executeQuery();
                             
                             rs1.next();
                             
                             String path ="D:\\javadirectories\\repos\\relever_note_t_"+rs1.getString("code_apogee")+"_"+id_demande+".pdf";
                             //open pdf fine
                             File myFile = new File(path);
                             Desktop.getDesktop().open(myFile);
                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erreur");
        }
    }//GEN-LAST:event_downloadActionPerformed

    private void envoyerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envoyerActionPerformed
        // TODO add your handling code here:
        try {
             CanvasLoop c = new CanvasLoop();
             c.setVisible(true);
            if(rs.getInt("semestre")==1){
                                                      
                             PreparedStatement pst1 =((PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select * from modules,etudiants,modules_etudiants,demande_docs,releve_notes where modules_etudiants.id_module = modules.id and modules_etudiants.id_etudiant=etudiants.id and demande_docs.id_etudiant = etudiants.id and releve_notes.id=demande_docs.id_demande and modules.niveau=? and etudiants.id=? and demande_docs.id_demande=?;"));
                             
                             String conca = niveau_e+Integer.toString(semestre);
                             pst1.setString(1,conca);
                             
                             pst1.setString(2,Integer.toString(id_etu));
                             
                             pst1.setString(3,Integer.toString(id_demande));
                             
                             ResultSet rs1 = pst1.executeQuery();
                             
                             rs1.next();
                             
                             String path ="D:\\javadirectories\\repos\\relever_note_"+rs1.getString("code_apogee")+"_"+id_demande+".pdf";
                             //open pdf fine
                             //File myFile = new File(path);
                             //Desktop.getDesktop().open(myFile);
                             
        
                             //variable de email
                             String email = rs1.getString("email_etudiant");
                             String bodymessage = "Votre relever de note";
                             String subject = "Tester email";
                             String myAdress = "porjetgenie.logiciel2022@gmail.com";
                             String passwordEMail = "genielogiciel";
                             String contenue = bodymessage;
                             String otherEmail = email;
                             //send file in email code
                             Properties properties = new Properties();
                             properties.put("mail.smtp.auth", "true");
                             properties.put("mail.smtp.starttls.enable", "true");
                             properties.put("mail.smtp.host", "smtp.gmail.com");
                             properties.put("mail.smtp.port", "587");
                             Session session = Session.getDefaultInstance(properties,new Authenticator() {
                                 @Override
                                 protected PasswordAuthentication getPasswordAuthentication() {
                                     return new PasswordAuthentication("porjetgenie.logiciel2022@gmail.com","trbqpsgfwezksylh");
                                 }
            
                             });
                             Message message = new MimeMessage(session);
                             message.setSubject(subject);
                             
                             message.setFrom(new InternetAddress(myAdress));
                             message.setRecipient(Message.RecipientType.TO, new InternetAddress(email));
                             message.setSentDate(new java.util.Date());
        
                             // Create the message part 
                                 BodyPart messageBodyPart = new MimeBodyPart();

                                 // Fill the message
                                 messageBodyPart.setText(bodymessage);
                                 // Create a multipar message
                                 Multipart multipart = new MimeMultipart();
            
                                 // Set text message part
                                 multipart.addBodyPart(messageBodyPart);

                                 // Part two is attachment
                                 messageBodyPart = new MimeBodyPart();
                                 String filename = path;
                                 DataSource source = new FileDataSource(filename);
                                 messageBodyPart.setDataHandler(new DataHandler(source));
                                 messageBodyPart.setFileName(filename);
                                 multipart.addBodyPart(messageBodyPart);

                                 // Send the complete message parts
                                 message.setContent(multipart);

                                 Transport.send(message);
                                 JOptionPane.showMessageDialog(null, "email sent");
                         }
                         else if(rs.getInt("semestre")==2){
                             PreparedStatement pst1 =((PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select * from modules,etudiants,modules_etudiants,demande_docs,releve_notes where modules_etudiants.id_module = modules.id and modules_etudiants.id_etudiant=etudiants.id and demande_docs.id_etudiant = etudiants.id and releve_notes.id=demande_docs.id_demande and modules.niveau=? and etudiants.id=? and demande_docs.id_demande=?;"));
                             
                             String conca = niveau_e+Integer.toString(semestre);
                             pst1.setString(1,conca);
                             
                             pst1.setString(2,Integer.toString(id_etu));
                             
                             pst1.setString(3,Integer.toString(id_demande));
                             
                             ResultSet rs1 = pst1.executeQuery();
                             
                             rs1.next();
                             
                             String path ="D:\\javadirectories\\repos\\relever_note_2_"+rs1.getString("code_apogee")+"_"+id_demande+".pdf";
                             //open pdf fine
                             //File myFile = new File(path);
                             //Desktop.getDesktop().open(myFile);
                             
        
                             //variable de email
                             String email = rs1.getString("email_etudiant");
                             String bodymessage = "Votre relever de note";
                             String subject = "Tester email";
                             String myAdress = "porjetgenie.logiciel2022@gmail.com";
                             String passwordEMail = "genielogiciel";
                             String contenue = bodymessage;
                             String otherEmail = email;
                             //send file in email code
                             Properties properties = new Properties();
                             properties.put("mail.smtp.auth", "true");
                             properties.put("mail.smtp.starttls.enable", "true");
                             properties.put("mail.smtp.host", "smtp.gmail.com");
                             properties.put("mail.smtp.port", "587");
                             Session session = Session.getDefaultInstance(properties,new Authenticator() {
                                 @Override
                                 protected PasswordAuthentication getPasswordAuthentication() {
                                     return new PasswordAuthentication("porjetgenie.logiciel2022@gmail.com","trbqpsgfwezksylh");
                                 }
            
                             });
                             Message message = new MimeMessage(session);
                             message.setSubject(subject);
                             
                             message.setFrom(new InternetAddress(myAdress));
                             message.setRecipient(Message.RecipientType.TO, new InternetAddress(email));
                             message.setSentDate(new java.util.Date());
        
                             // Create the message part 
                                 BodyPart messageBodyPart = new MimeBodyPart();

                                 // Fill the message
                                 messageBodyPart.setText(bodymessage);
                                 // Create a multipar message
                                 Multipart multipart = new MimeMultipart();
            
                                 // Set text message part
                                 multipart.addBodyPart(messageBodyPart);

                                 // Part two is attachment
                                 messageBodyPart = new MimeBodyPart();
                                 String filename = path;
                                 DataSource source = new FileDataSource(filename);
                                 messageBodyPart.setDataHandler(new DataHandler(source));
                                 messageBodyPart.setFileName(filename);
                                 multipart.addBodyPart(messageBodyPart);

                                 // Send the complete message parts
                                 message.setContent(multipart);

                                 Transport.send(message);
                                 JOptionPane.showMessageDialog(null, "email sent");
                         }
                         else{
                             PreparedStatement pst1 =((PreparedStatement) ConnectionDB.getConnexion().prepareStatement("select * from modules,etudiants,modules_etudiants,demande_docs,releve_notes where modules_etudiants.id_module = modules.id and modules_etudiants.id_etudiant=etudiants.id and demande_docs.id_etudiant = etudiants.id and releve_notes.id=demande_docs.id_demande and (modules.niveau=? or modules.niveau=?) and etudiants.id=? and demande_docs.id_demande=?;"));
                             
                             String conca = niveau_e+"1";
                             String conca2 = niveau_e+"2";
                             pst1.setString(1,conca);
                             
                             pst1.setString(2,conca2);
                             
                             pst1.setString(3,Integer.toString(id_etu));
                             
                             pst1.setString(4,Integer.toString(id_demande));
                             
                             ResultSet rs1 = pst1.executeQuery();
                             
                             rs1.next();
                             
                             String path ="D:\\javadirectories\\repos\\relever_note_t_"+rs1.getString("code_apogee")+"_"+id_demande+".pdf";
                             //open pdf fine
                             //File myFile = new File(path);
                             //Desktop.getDesktop().open(myFile);
                             
        
                             //variable de email
                             String email = rs1.getString("email_etudiant");
                             String bodymessage = "Votre relever de note";
                             String subject = "Tester email";
                             String myAdress = "porjetgenie.logiciel2022@gmail.com";
                             String passwordEMail = "genielogiciel";
                             String contenue = bodymessage;
                             String otherEmail = email;
                             //send file in email code
                             Properties properties = new Properties();
                             properties.put("mail.smtp.auth", "true");
                             properties.put("mail.smtp.starttls.enable", "true");
                             properties.put("mail.smtp.host", "smtp.gmail.com");
                             properties.put("mail.smtp.port", "587");
                             Session session = Session.getDefaultInstance(properties,new Authenticator() {
                                 @Override
                                 protected PasswordAuthentication getPasswordAuthentication() {
                                     return new PasswordAuthentication("porjetgenie.logiciel2022@gmail.com","trbqpsgfwezksylh");
                                 }
            
                             });
                             Message message = new MimeMessage(session);
                             message.setSubject(subject);
                             
                             message.setFrom(new InternetAddress(myAdress));
                             message.setRecipient(Message.RecipientType.TO, new InternetAddress(email));
                             message.setSentDate(new java.util.Date());
        
                             // Create the message part 
                                 BodyPart messageBodyPart = new MimeBodyPart();

                                 // Fill the message
                                 messageBodyPart.setText(bodymessage);
                                 // Create a multipar message
                                 Multipart multipart = new MimeMultipart();
            
                                 // Set text message part
                                 multipart.addBodyPart(messageBodyPart);

                                 // Part two is attachment
                                 messageBodyPart = new MimeBodyPart();
                                 String filename = path;
                                 DataSource source = new FileDataSource(filename);
                                 messageBodyPart.setDataHandler(new DataHandler(source));
                                 messageBodyPart.setFileName(filename);
                                 multipart.addBodyPart(messageBodyPart);

                                 // Send the complete message parts
                                 message.setContent(multipart);

                                 Transport.send(message);
                                 c.dispose();
                                 JOptionPane.showMessageDialog(null, "email sent");
                                 Archive ar = new Archive();
                                 ar.setVisible(true);
                                 this.dispose();
                         }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
 
    }//GEN-LAST:event_envoyerActionPerformed

    private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_XActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Releve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Releve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Releve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Releve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Releve().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button X;
    private javax.swing.JButton deconnecter;
    private javax.swing.JButton download;
    private javax.swing.JButton envoyer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel6;
    private javax.swing.JButton menu;
    private javax.swing.JTextField niveau;
    private javax.swing.JButton retour;
    private javax.swing.JPanel semesterRadio;
    // End of variables declaration//GEN-END:variables
}
